os: linux
dist: trusty
language: node_js
node_js:
  - 10
cache: npm
script:
  - npm run build
after_success:
  - scripts/update.sh
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release --no-install
