const fs = require('fs')
const path = require('path')

const snippets = require('../submodules/30-seconds-of-code/snippet_data/snippets.json')

const NEWLINE = '\n'
const FILENAME = '30secondsofcode.snippets'
const HEADER = `# Generated by 30-seconds-of-code-ultisnips
# (https://github.com/sQVe/30-seconds-of-code-ultisnips/)
# -------------------------------------------------------

`

const isDefinedData = (arr) => arr.every((x) => x != null)

const createSafeUltiSnipsDescription = (text) =>
  text.replace(/\s/g, ' ').replace(/"/g, '')

const createUltiSnipsSnippet = ({
  id,
  attributes: {
    codeBlocks: { es6 },
    text,
  },
}) =>
  isDefinedData([id, es6, text])
    ? [
        `snippet ${id} "${createSafeUltiSnipsDescription(text)}" b`,
        es6,
        'endsnippet',
      ].join(NEWLINE)
    : process.exit(1)

function writeSnippetsFile() {
  fs.writeFileSync(
    path.resolve(__dirname, `../dist/UltiSnips/${FILENAME}`),
    HEADER + snippets.data.map(createUltiSnipsSnippet).join(NEWLINE + NEWLINE)
  )

  return console.log(`Successfully created ${FILENAME} file.`) // eslint-disable-line no-console
}

writeSnippetsFile()
