name: Auto update snippets

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          submodules: recursive

      - name: Update snippets
        run: scripts/update.sh
